### ISSUE TITLE
Running into errors when running locally

### ISSUE THREAD

**Issue by cachemoney** [winkerVSbecks/solarstorm#2]
Hello,
I was running into issues when running this locally, in both Safari and Firefox.  I have Node 16, LTS, yarn 1.22.17.  Are there settings in the browser to be set to have this run locally?  Thanks!

![image](https://user-images.githubusercontent.com/477635/154749502-89f9e8c6-58f6-412e-90ec-e15f62491e53.png)

**Comment by winkerVSbecks** [comment]
looks like a dependency versioning issue. Did you use yarn? I have a lockfile to install the correct versions.

**Comment by cachemoney** [comment]
wow this is strange, When I visit localhost, I get the errors, but when I go on the "network" it seems to work fine.  Have you come across that issue before?  I guess this issue can be closed.  thanks.

![image](https://user-images.githubusercontent.com/477635/154771102-d6be6ccd-f3ad-4bcd-8de1-35cf0ad2fd36.png)

**Comment by winkerVSbecks** [comment]
Never seen that before, strange. Might be something to do with loading static assets.
